### ISSUE TITLE
Validation error on Nil Type usage

### ISSUE THREAD

**Issue by akshay-8d66** [mulesoft/api_project_maven_client#12]
The following RAML Nil Type usage should be valid based on the [NilType spec](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#nil-type), however it fails validation.

```
#%RAML 1.0
title: Demonstrate validation bug
types:
  User:
    type: object
    properties:
      age:
        type: integer | nil
        maximum: 100
```

> Property 'maximum' not supported in a RAML 1.0 union node at (9, 9)

The workaround to express the equivalent in a much more verbose way is like this:

```
#%RAML 1.0
title: Workaround for validation bug
types:
  Age:
    type: integer
    maximum: 100
  User:
    type: object
    properties:
      age:
        type: Age | nil
```

It would be super if this scenario could be supported.
